WIP: Add support for reading gstlal trigger files
gwpy/gwpy pull request #1265
Opened 2020-08-19 20:43 UTC by dethodav

This pull request aims to add support for reading gstlal trigger files.

The rationale for a specific gstlal format is 

* A desire to calculate some useful derived quantities. This feature is available for only pycbc trigger files at present. 
* The gstlal statistic requires additional inputs beyond what is included in trigger files in order to calculate the ranking statistic. However, the comparable quantity is stored in the `coinc_event` table. Hence reading in both the `coinc_event` and `coinc_inspiral` tables at once would be a useful feature. 

Thew new proposed format heavily relies upon the current ligolw functionality, with the addition of the two features above.

2020-08-19 20:43 UTC, pep8speaks commented
Hello @dethodav! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`gwpy/table/io/gstlal.py`](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py):

> [Line 40:1](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L40): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 50:45](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L50): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 69:80](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L69): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 74:80](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L74): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 82:39](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L82): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 91:80](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L91): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 93:13](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L93): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 93:23](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L93): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 93:25](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L93): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 93:80](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L93): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 94:30](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L94): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 94:30](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L94): [E113](https://duckduckgo.com/?q=pep8%20E113) unexpected indentation
> [Line 95:13](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L95): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 95:32](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L95): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 97:13](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L97): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 97:27](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L97): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 97:29](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L97): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 97:80](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L97): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)
> [Line 98:13](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L98): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 98:24](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L98): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 98:26](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L98): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 98:80](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L98): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 99:9](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L99): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 99:13](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L99): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 100:27](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L100): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 100:29](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L100): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 100:80](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L100): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 101:24](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L101): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 101:26](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L101): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 102:9](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L102): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 102:15](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L102): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 102:17](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L102): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 104:9](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L104): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 104:33](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L104): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 104:35](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L104): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 105:5](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/io/gstlal.py#L105): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 105:9](https://github.com/gwpy/gwpy/blob/5c9dbf3d0f50d367715068a54e572e5396399d79/gwpy/table/i [...]

2020-08-19 20:45 UTC, dethodav commented
At present, this pull request is not ready for merge - one of the remaining items is setting up the necessary registry in the format file. @duncanmmacleod @alurban Would you be able to help explain how the file registry is set up?

2021-03-02 10:45 UTC, duncanmmacleod commented
@dethodav, is this still a desired change? If 'yes' (I hope so) then I can help get things straightened out, tested, reviewed, and merged.

First up, please `rebase` against the upstream `master` branch.

2021-03-23 17:30 UTC, dethodav commented
@duncanmmacleod Yes, I would still be interested in adding this feature to gwpy. I've gone ahead and rebased to the current main branch and updated the PR. Let me know your suggested next steps.

2021-06-29 09:49 UTC, duncanmmacleod commented
@dethodav, I let this linger again, please rebase. I think the PEP8/flake linter issues are real, so please have a look at those.

Please think also about how to add tests of the new functionality.

2022-07-18 12:52 UTC, duncanmmacleod commented on gwpy/table/io/gstlal.py
> +    return False
@dethodav, the `identify_gstlal` function should take in the arguments are you have them listed, and inspect them to unimbiguously detect whether the incoming file is a 'gstlal file' (returning `True`) or not (`False`).

For PyCBC we do this with a regular expression on the filename, which isn't great, but seems to work well enough.

What is unique about a GstLAL file?

2022-08-30 15:04 UTC, dethodav commented
@duncanmmacleod Here is an example gstlal xml file (available at CIT): `/home/gstlalcbc/observing/4/dev/runs/trigs.edward_O3_replay_MDC06/13443/H1L1V1-0598_noninj_LLOID-1344312382-14414.xml.gz`

2022-09-01 19:14 UTC, dethodav commented
@duncanmmacleod I've gone through and made updates to this PR. Things should be ready for review modulo the failing "Dependencies" check. Do you have any suggestions on how best to resolve this import issue?

2022-09-02 08:14 UTC, duncanmmacleod requested changes
> @duncanmmacleod I've gone through and made updates to this PR. Things should be ready for review modulo the failing "Dependencies" check. Do you have any suggestions on how best to resolve this import issue?

Thanks @dethodav, the fundamental issue here is that `python-ligo-lw` is not a first-class requirement of GWpy, it's optional. So you need to protect the imports in `gwpy/table/io/gstlal.py` and `gwpy/table/tests/test_io_gstlal.py` so that the test suite executes without it.

Refer to `gwpy/table/io/ligolw.py` and `gwpy/table/tests/test_io_ligolw.py` for inspiration there.

You will also need to add a reference to the new `gstlal` module in `gwpy/table/io/__init__.py` so that the I/O format is registered automatically when the `EventTable` is first imported.

2022-09-13 13:45 UTC, dethodav commented
@duncanmmacleod I've now addressed the rest-related issues. Let me know if there's anything else that needs to be fixed before merger.

2022-09-15 14:30 UTC, duncanmmacleod approved these changes
Thanks for this @dethodav, looks great.

2022-09-15 14:30 UTC, merged