Split up functionality of TimeSeries.gate()
gwpy/gwpy pull request #1494
Opened 2022-05-04 21:59 UTC by dethodav

This PR splits `TimeSeries.gate()` into two functions:
* `TimeSeries.find_gates()` - find peaks in whitened timeseries and returns the segments to gate
* `TimeSeries.gate()` - now only calls `TimeSeries.find_gates()` and `TimeSeries.mask()` to find and apply gates

The motivation for this change is that it would be helpful to be able to record the segments that were gated. Users hoping to do this can now use `TimeSeries.find_gates()` and `TimeSeries.mask()` separately. 

Since this PR is only reorganizing code, the result of `TimeSeries.gate()` remains unchanged.

2022-05-04 21:59 UTC, pep8speaks commented
Hello @dethodav! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`gwpy/timeseries/timeseries.py`](https://github.com/gwpy/gwpy/blob/a62368181887b2a06a48335b90725bf41dd91194/gwpy/timeseries/timeseries.py):

> [Line 1809:14](https://github.com/gwpy/gwpy/blob/a62368181887b2a06a48335b90725bf41dd91194/gwpy/timeseries/timeseries.py#L1809): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 1932:48](https://github.com/gwpy/gwpy/blob/a62368181887b2a06a48335b90725bf41dd91194/gwpy/timeseries/timeseries.py#L1932): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1933:14](https://github.com/gwpy/gwpy/blob/a62368181887b2a06a48335b90725bf41dd91194/gwpy/timeseries/timeseries.py#L1933): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 1933:49](https://github.com/gwpy/gwpy/blob/a62368181887b2a06a48335b90725bf41dd91194/gwpy/timeseries/timeseries.py#L1933): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1934:14](https://github.com/gwpy/gwpy/blob/a62368181887b2a06a48335b90725bf41dd91194/gwpy/timeseries/timeseries.py#L1934): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

2022-05-05 12:58 UTC, duncanmmacleod requested changes
Thanks @dethodav, this will be a nice addition, I have a few pedantic requests.

2022-05-05 12:58 UTC, duncanmmacleod commented on gwpy/timeseries/timeseries.py
> +        See also
Need a blank line here

```suggestion

        See also
```

2022-05-05 12:58 UTC, duncanmmacleod commented on gwpy/timeseries/timeseries.py
> +        from scipy.signal import find_peaks
`scipy.signal` is already imported at the module level, so this is not required

```suggestion
```

(I realise that this line was already here, but let's fix it anyway)

2022-05-05 12:58 UTC, duncanmmacleod commented on gwpy/timeseries/timeseries.py
> +        gates = find_peaks(abs(data.value), height=threshold,
As above

```suggestion
        gates = signal.find_peaks(abs(data.value), height=threshold,
```

2022-05-05 12:58 UTC, duncanmmacleod commented on gwpy/timeseries/timeseries.py
> +        return deadtime
```suggestion
        return SegmentList([Segment(
            self.t0.value + (k / sample) - tzero,
            self.t0.value + (k / sample) + tzero,
        ) for k in gates]).coalesce()
```

2022-05-05 12:58 UTC, duncanmmacleod commented on gwpy/timeseries/timeseries.py
>          return self.mask(deadtime=deadtime, const=0, tpad=tpad)
The name `gates` I think would be clearer here.

```suggestion
        gates = self.find_gates(tzero=tzero, whiten=whiten,
                                   threshold=threshold,
                                   cluster_window=cluster_window,
                                   **whiten_kwargs)
        return self.mask(deadtime=gates, const=0, tpad=tpad)
```

2022-05-06 16:51 UTC, dethodav commented
@duncanmmacleod All your suggestions should now be implemented

2022-05-20 16:43 UTC, dethodav commented
While making a "main" branch on my fork, I seem to have inadvertently closed this PR. I've now reopened it.

2022-08-25 11:16 UTC, duncanmmacleod approved these changes
LGTM, thanks @dethodav.

2022-08-25 11:16 UTC, merged