Fix plotting of transfer function from command line
gwpy/gwpy pull request #1535
Opened 2022-08-09 01:07 UTC by eagoetz

Replace a simple Plot with BodePlot for plotting the magnitude and phase of a transfer function measurement

Closes #1526

2022-08-10 13:29 UTC, duncanmmacleod requested changes
@eagoetz, thanks for getting to this! Unfortunately this minimal change is not enough. This is because a `BodePlot` has two `Axes`, that need to be handled separately. So lines like

https://github.com/gwpy/gwpy/blob/5ff099c8b9d2497325e4522f76c546d04452f4c0/gwpy/cli/transferfunction.py#L109

don't do what you need them to do.

You will need to refactor the `make_plot` function to use something like `plot.add_frequencyseries` instead of `ax.plot` when iterating over the data.

You can see that the complex arrays are still being handled badly by running

```shell
python -m pytest gwpy/cli/tests/test_transferfunction.py
```

and inspecting the warnings that pytest propagates.

2022-08-10 15:13 UTC, eagoetz commented
@duncanmmacleod Thanks for replying super fast. It's weird, I ran this command but didn't spot any warnings, but I could have missed them in my haste. I'll check again on this today and try to get this resolved quickly.

2022-08-24 10:29 UTC, duncanmmacleod commented
Ping @eagoetz.

2022-08-24 18:00 UTC, eagoetz commented
@duncanmmacleod Yeah, I've been looking at this and it's more complicated than I anticipated. I'll try to get this soon, but I cannot say for sure it will be done before the end of August. I'm trying though

2022-08-30 23:35 UTC, eagoetz commented
@duncanmmacleod I've re-requested review of this. Please let me know what improvements you think I ought to make. Thank you in advance!

2022-09-01 16:16 UTC, duncanmmacleod requested changes
@eagoetz, I have put in some specific comments below, but I want to sit and stare at this code for a while to work out what the best route to solution is.

I think there should be a way to make the whole system more generic in terms of figures with multiple axes, which might help you to implement this specific instance.

So, don't get to work on fixing the minutia I have pointed out just yet, let's talk next week.

2022-09-01 16:16 UTC, duncanmmacleod commented on gwpy/cli/transferfunction.py
> +            self.set_yaxis_properties()
I'm not a fan of using an instance variable for internal state keeping like this. Would it just be better to have the individual methods operate over both (generally 'all') axes internally?

2022-09-01 16:16 UTC, duncanmmacleod commented on gwpy/cli/transferfunction.py
> +                ret = getattr(self.plot.axes[self.subplot], f'get_x{param}')()
I think this can be simplified:

```suggestion
            ret = getattr(self.plot.axes[self.subplot], f'get_{axis[0].lower()}{param}')()
```

2022-09-01 16:16 UTC, duncanmmacleod commented on gwpy/cli/transferfunction.py
> +                ret = getattr(self.plot.axes[self.subplot], f'get_x{param}')()
There a number of similar cases below. I think overloading the `axis` property for `ymag` and `yphase` is a bit odd, can't really verbalise why.

2022-09-01 23:45 UTC, eagoetz commented
@duncanmmacleod Thanks for the comments. I fixed the minor things you pointed out, but I agree the code structure makes it a bit clunky to work with plots that have multiple axes. I doubt this was ever envisioned with the original CLI structure, so it makes sense that this is hard to work with. I'll be happy to discuss with you further next week. Cheers!

2022-09-17 13:35 UTC, duncanmmacleod approved these changes
As discussed in person, we should merge this now and then generalise it later. Thanks @eagoetz!

2022-09-17 13:35 UTC, merged