Address floating point errors for index creation
gwpy/gwpy pull request #1600
Opened 2023-03-28 23:03 UTC by dethodav

This PR addresses #1596 and introduces a new test to confirm that this issue does not pop up again with the `Index` class.

2023-04-03 23:03 UTC, dethodav commented
@duncanmmacleod Is this a reasonable way to fix this bug? This is causing issues right now with DQR tasks.

2023-04-04 10:55 UTC, duncanmmacleod requested changes
@dethodav, floats are tricksy, so I think this is probably 'good enough' if it avoids the issues you reported.

Thanks for adding a regression test, that will help maintenance in the future.

I have requested one pedantic stylistic change, then we're good to go.

2023-04-04 10:55 UTC, duncanmmacleod commented on gwpy/types/index.py
> +                         step.value, dtype=dtype)[:num],
```suggestion
            numpy.arange(
                start.value,
                stop.value,
                step.value,
                dtype=dtype,
            )[:num],
```

2023-04-04 17:13 UTC, dethodav commented
@duncanmmacleod thanks! I just implemented your suggestion

2023-04-06 10:34 UTC, duncanmmacleod approved these changes
Thanks @dethodav, looks great.

2023-04-06 10:34 UTC, merged